### Задание на повторение материала

### Задание 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

In [4]:
a = np.array([_ for _ in range(12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [19]:
a_1 = a.reshape(2,6)
a_2 = a.reshape(6,2)
a_3 = a.reshape(3,4)
a_4 = a.reshape(4,3)
a_5 = a.reshape(12,1)
a_1, a_2, a_3, a_4, a_5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

### Задание 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [24]:
ar_1 = a.reshape(-1, 3)
ar_2 = a.reshape(-1, 2)
ar_3 = a.reshape(-1, 4)
ar_4 = a.reshape(2, -1)
ar_5 = a.reshape(12, -1)
ar_1, ar_2, ar_3, ar_4, ar_5

(array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

### Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [26]:
# Нет, это двумерный массив.

### Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [30]:
b = 1.0 * np.random.randn(3,4) + 0
b

array([[ 0.08913983, -1.91003026, -0.40130746, -0.123587  ],
       [-0.02148156,  0.34616734,  1.4321773 , -0.11785818],
       [ 1.1728444 , -1.07955941, -0.72453   , -0.05553386]])

### Задание 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [33]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [41]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [42]:
# Массив b является многомерным

### Задание 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [54]:
a = np.zeros((2,2) ,int)
b = np.ones((3,2), int)
a, b

(array([[0, 0],
        [0, 0]]),
 array([[1, 1],
        [1, 1],
        [1, 1]]))

In [61]:
v = np.vstack((a, b))
v

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

In [62]:
v.size

10

### Задание 9


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [63]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [69]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [70]:
B.size

16

In [72]:
# обратную матрицу вычислить невозможно.

### Задание 10


 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [75]:
np.random.seed(42)